# Generated by Django 3.0.8 on 2020-07-31 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricketer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_Cricketer', models.CharField(choices=[('Sachin_Tendulkar', 'Sachin_Tendulkar'), ('Virat_Kolli', 'Virat_Kolli'), ('Adam_Gilchirst', 'Adam_Gilchirst'), ('Jacques_Kallis', 'Jacques_Kallis')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cricketerforo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricketerforo', to='app.Cricketer')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indian_National_Flag', models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_Name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketerfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricketerfor', to='app.Cricketer')),
                ('finishfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishfor', to='app.Finish')),
                ('flagfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagfor', to='app.Flag')),
                ('namefor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namefor', to='app.Name')),
            ],
        ),
        migrations.AddField(
            model_name='finish',
            name='flagforo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagforo', to='app.Flag'),
        ),
        migrations.AddField(
            model_name='finish',
            name='nameforo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameforo', to='app.Name'),
        ),
    ]
